---
dependency:
  name: galaxy
  options:
    ignore-errors: True
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: $TOX_ENVNAME
    image: nmusatti/${TOX_ENVNAME}-pys
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      ALLOW_BROKEN_CONDITIONALS: true
verifier:
  name: testinfra
